apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi #capacity of the nfs server
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local #cluster ip of nfs-service or <service-name>.<namespace>.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi #storage claim upto the capacity of the nfs server
